apiVersion: skaffold/v4beta7
kind: Config
metadata:
  name: blueberry-service
build:
  artifacts:
    - image: blueberry-image
manifests:
  rawYaml: []
deploy:
  cloudrun: {}

## Cloud Deploy가 verify: true일 때 오류 방지를 위한 dummy verify
#verify:
#  - name: noop-verify
#    container:
#      name: verify
#      image: busybox:latest
#      command: ["sh", "-c", "echo 'Skipping verify stage (manual deploy)'; exit 0"]

profiles:
  - name: staging
    manifests:
      rawYaml:
        - lightship-staging.yaml
  - name: production
    manifests:
      rawYaml:
        - lightship-production.yaml
